version: '3'

services:
  back:
    build: back/.
    environment:
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db

  front:
    build: front/.
    ports:
     - "8080:8080"

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - '5432:5432'
    volumes:
        - ./postgres_data:/var/lib/postgresql/data

  matchs-provider:
    build: matchs-provider/.
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
        - db